// Register.tsx
import React, { useState } from 'react';

const RegistrationForm = () => {
  const [name, setName] = useState<string>('');
  const [email, setEmail] = useState<string>('');
  const [password, setPassword] = useState<string>('');

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    const response = await fetch('https://example.com/api/register', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ name, email, password }),
    });

    if (response.ok) {
      alert('Registration successful!');
    } else {
      alert('Registration failed. Please try again.');
    }
  };

  return (
    <div>
      <h1>Registration Form</h1>
      <form onSubmit={handleSubmit}>
        <label>
          Name:
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
          />
        </label>
        <label>
          Email:
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
          />
        </label>
        <label>
          Password:
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
        </label>
        <button type="submit">Register</button>
      </form>
    </div>
  );
};

export default RegistrationForm;

// Register.svelte
<script>
    let name = '';
    let email = '';
    let password = '';
  
    const handleSubmit = async () => {
      const response = await fetch('https://example.com/api/register', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ name, email, password }),
      });
  
      if (response.ok) {
        alert('Registration successful!');
      } else {
        alert('Registration failed. Please try again.');
      }
    };
  </script>
  
  <main>
    <h1>Registration Form</h1>
    <form on:submit|preventDefault={handleSubmit}>
      <label>
        Name:
        <input bind:value={name} type="text" required />
      </label>
      <label>
        Email:
        <input bind:value={email} type="email" required />
      </label>
      <label>
        Password:
        <input bind:value={password} type="password" required />
      </label>
      <button type="submit">Register</button>
    </form>
  </main>
